# Generated by Django 5.2 on 2025-05-06 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('ACAO', 'Ação'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comédia'), ('DRAMA', 'Drama'), ('FICCAO', 'Ficção Científica'), ('TERROR', 'Terror'), ('ROMANCE', 'Romance'), ('FANTASIA', 'Fantasia'), ('SUSPENSE', 'Suspense'), ('MISTERIO', 'Mistério'), ('GUERRA', 'Guerra'), ('FAROESTE', 'Faroeste'), ('MUSICAL', 'Musical'), ('ANIMACAO', 'Animação'), ('OUTROS', 'Outros')], max_length=15),
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='filme.filme')),
            ],
        ),
    ]
